language: node_js
node_js:
 - "node"

environment:
  nodejs_version: "6"


install:
  - ps: Install-Product node 6
  - npm install
  - npm install --save-dev should
  - npm install --save-dev expect
  
deploy:
  provider: releases
  user: "OlyaGasanova"
  password: "lifeonmars123"
  file: /.*\.zip/
  skip_cleanup: true
  on:
    tags: false
    
artifacts:
    - path: /

test_script:
  - node --version
  - npm --version
  - npm test    
