branches:
  only:
    - master

environment:
  nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test


build: off

test: off

services:
  - mongodb
before_deploy:
  - PowerShell .\InstallSelfSignedCert.ps1
artifacts:
    - path: file1.pkg
    - path: file2.pkg
    - ...

deploy:
    provider: GitHub                         
    description: '$(APPVEYOR_REPO_TAG_NAME)'

    auth_token:
        secure: g3esyoKixmjCE1S+Lx3zUdbYPacwOHRePMEydE0FVzVaXC4LqBoYcJpAoT/j6lLd

    artifact: /.*\.pkg/
    force_update: true 

    on:
        appveyor_repo_tag: true 
