branches:
  only:
    - master

environment:
  nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test


build: off

test: off

services:
  - mongodb
before_deploy:
  - PowerShell .\InstallSelfSignedCert.ps1
artifacts:
    - path: /

deploy:
    provider: GitHub                         
    description: '$(APPVEYOR_REPO_TAG_NAME)'

    auth_token:
      secure: 'W5TNL7xbdAbA+rYkAECXJ7OTFknNd7s3zkhssB4PB/Yv3TLCSArtRT1K/PlIShNf'
    
    artifact: /.*\/
    force_update: true 

    on:
        appveyor_repo_tag: false 
