branches:
  only:
    - master

environment:
  nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm install --save-dev should
  - npm install --save-dev expect

test_script:
  - node --version
  - npm --version
  - npm test


build: off

test: npm test

services:
  - mongodb

artifacts:
    - path: /

deploy:
    provider: GitHub                         
    description: '$(APPVEYOR_REPO_TAG_NAME)'

    auth_token:
      secure: 'W5TNL7xbdAbA+rYkAECXJ7OTFknNd7s3zkhssB4PB/Yv3TLCSArtRT1K/PlIShNf'
    
    artifact: /.*\.zip/
    force_update: true 

    on:
        appveyor_repo_tag: false 
