branches:
  only:
    - master

environment:
  nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

# Don't actually build.
build: off

before_deploy:
  - PowerShell .\InstallSelfSignedCert.ps1
=======
build: off

test: off

services:
  - mongodb
  
before_deploy:
  - PowerShell .\InstallSelfSignedCert.ps1
